swagger: "2.0"
info:
  description: "[QuizWiki](https://www.quiz-wiki.com/)のバックエンドです。"
  version: "1.0.0"
  title: "wiki-quiz-api-spec"
tags:
  - name: "Question"
    description: "クイズの問題に関するAPI"
schemes:
  - "http"
paths:
  /v1/question:
    get:
      tags:
        - "Question"
      summary: "問題データの取得"
      description: "問題文を取得します"
      responses:
        200:
          description: "正しいレスポンス"
          schema:
            type: "object"
            properties:
              title:
                type: "string"
                example: "問題文のタイトル"
              categories:
                type: "array"
                items:
                  type: "string"
                example:
                  - "カテゴリー1"
                  - "カテゴリー2"
                  - "カテゴリー3"
              words:
                type: "array"
                items:
                  type: "string"
                example:
                  - "ワード1"
                  - "ワード2"
                  - "ワード3"
                  - "ワード4"
                  - "ワード5"
                  - "ワード6"
                  - "ワード7"
                  - "ワード8"
                  - "ワード9"
              images:
                type: "string"
                example: "www.image.png"
              url:
                type: "string"
                example: "www.wikipekia.com"
        500:
          description: "MediaWikiとの接続に失敗。またはスクリプトエラー"
  /v1/question/confirm:
    get:
      tags:
        - "Question"
      summary: "回答と一致するかを検証"
      description: "Wikipediaの記事データをランダムで取得します"
      parameters:
        - name: "searchWord"
          in: "query"
          description: "検索をかけてほしい回答"
          required: true
          type: "string"
        - name: "answer"
          in: "query"
          description: "答え"
          required: true
          type: "string"
      responses:
        200:
          description: "成功時のレスポンス"
          schema:
            type: "object"
            properties:
              isCorrect:
                type: "boolean"
                example: "true"
        500:
          description: "MediaWikiとの接続に失敗。またはスクリプトエラー"
