swagger: "2.0"
info:
  description: "[QuizWiki](https://www.quiz-wiki.com/)のAPI仕様書です。"
  version: "2.0.0"
  title: "wiki-quiz-api-spec"
tags:
  - name: "Question"
    description: "クイズの問題に関するAPI"
host: wiki-quiz-backend-dev.an.r.appspot.com
basePath: /v2
schemes:
  - "https"
  - "http"
paths:
  /question:
    get:
      tags:
        - "Question"
      summary: "問題データの取得"
      description: "問題文を取得します"
      responses:
        200:
          description: "正しいレスポンス"
          schema:
            $ref: "#/definitions/Question"
            properties:
              title:
                type: "string"
                example: "問題文のタイトル"
              categories:
                type: "array"
                items:
                  type: "string"
                example:
                  - "カテゴリー1"
                  - "カテゴリー2"
                  - "カテゴリー3"
              words:
                type: "array"
                items:
                  type: "string"
                example:
                  - "ワード1"
                  - "ワード2"
                  - "ワード3"
                  - "ワード4"
                  - "ワード5"
                  - "ワード6"
                  - "ワード7"
                  - "ワード8"
                  - "ワード9"
              images:
                type: "string"
                example: "www.image.png"
              url:
                type: "string"
                example: "www.wikipekia.com"
        500:
          description: "MediaWikiとの接続に失敗。またはスクリプトエラー"
  /question:confirm:
    post:
      tags:
        - "Question"
      summary: "回答と一致するかを検証"
      description: "Wikipediaの記事データをランダムで取得します"
      parameters:
        - in: "body"
          name: "body"
          description: "Pet object that needs to be added to the store"
          required: true
          schema:
            $ref: "#/definitions/ConfirmReq"
      responses:
        200:
          description: "成功時のレスポンス"
          schema:
            $ref: "#/definitions/Confirm"
            properties:
              isCorrect:
                type: "boolean"
                example: "true"
        400:
          description: "searchWordが空欄。"
        500:
          description: "MediaWikiとの接続に失敗。またはスクリプトエラー"
definitions:
  Question:
    type: "object"
    properties:
      title:
        type: "string"
      categories:
        type: "array"
        items:
          type: "string"
      words:
        type: "array"
        items:
          type: "string"
      images:
        type: "string"
      url:
        type: "string"
  Confirm:
    type: "object"
    properties:
      isCorrect:
        type: boolean
  ConfirmReq:
    type: "object"
    properties:
      searchWord:
        type: string
        example: "問題文のタイトル"
      answer:
        type: string
        example: "答え"
